### ISSUE TITLE
MMRecord Primary Key for Relationship in API response causing crash

### ISSUE THREAD

**Issue by startupthekid** [mutualmobile/MMRecord#101]
I have the follow models defined for my app 

    User {
        userID: String,
        facebookId: String,
        twitterId: String,
        firstName: String
        lastName: String,
        email: String,
        username: String,
        created: NSDate,
        updated: NSDate,
        posts:  [Post], //array/set of posts
        lofts: [Loft], //array/set of lofts
        likedPosts: [Post] //list of posts the user has liked
    }
    Loft {
        loftID: String,
        name: String,
        latitude: Double,
        longitude: Double,
        radius: Double,
        private: Bool,
        created: NSDate,
        updated: NSDate,
        members: [User], //array/set of users
        posts: [Post] //array/set of posts
    }
    Post {
        postID: String,
        created: NSDate,
        updated: NSDate,
        poster: User,
        likes: [User], //list of users that have liked the post,
        loft: Loft, //group the post belongs to
    }

I also have a subentity of Post, TextPost that's simply this:

    TextPost {
        text: String
    }

The relationships are defined as following:

`User.posts` -> `Post.poster` //One to many
`User.lofts` -> `Loft.members` //Many to Many
`Loft.posts` -> `Post.loft` //One to many
`Post.likes` -> `User.likedPosts` //Many to Many

When I initially launch the app, I first make a get request for the user model and get back this response:

    {
        "__v" = 1;
        "_id" = 54af04c434cb9aaf09f01ece;
        comments =         (
        );
        created = "2015-01-08T22:29:24.054Z";
        email = "conronb@gmail.com";
        facebookId = 1058664964;
        firstName = Brendan;
        image =         {
            name = "g0s4B826LtkcJdOhZ23Scof_.png";
            size = 776378;
            type = "image/png";
            url = "https://swoopy-loft.s3.amazonaws.com/user/g0s4B826LtkcJdOhZ23Scof_.png";
        };
        lastName = Conron;
        likedPosts =         (
        );
        lofts =         (
            54af04de34cb9aaf09f01ecf
        );
        posts =         (
            54af051934cb9aaf09f01ed0
        );
        twitterId = "";
        updated = "2015-01-08T22:29:24.055Z";
        username = thebear;
    }

MMRecord does fine when it hits the `lofts` relationship; a new loft model entity is created with that primary id key. When it hits the `posts` relationships however, things go a little screwy. The app crashes on `subEntityForRecordResponseObject:withInitialEntity` because inside of that method, when checking `shouldUseSubEntityRecordClassToRepresentData`, the object passed is an instance of `__NSCFString` and `count` is trying to be called on the object as if it were a dictionary. The value being passed in to the `TextPost` class (which inherits from Post and returns true in `shouldUseSubEntityRecordClassToRepresentData`) in this case is `54af051934cb9aaf09f01ed0`, the backend id of the post from MongoDB.

Here's the call stack from Xcode (crashes on the top).

    [MMRecordResponse subEntityForRecordResponseObject:withInitialEntity:]
    [MMRecordResponse addRelationshipProtoRecordsToProtoRecord:existingResponseGroups:representation:relationshipDescription:]
    [MMRecordResponse completeRelationshipProtoRecordMappingToProtoRecord:existingResponseGroups:representation:]     
    [MMRecordResponse protoRecordWithRecordResponseObject:entity:existingResponseGroups:parentProtoRecord:]        
    [MMRecordResponse buildProtoRecordsAndResponseGroups]
    [MMRecordResponse records] 
    [MMRecord recordsFromResponseObject:options:state:context:]
    [MMRecord completeRequestForResponse:state:options:]
    [MMRecord performRequestWithRequestState:]

I understand what's happening on a higher level, essentially when the relationships of an entity are being populated and going through possible sub entities, the id of a post gets passed where it shouldn't be, thus the crash. 
What's confusing though is that the `lofts` property is retrieved in the same way, just an array of ids but MMRecord correctly tries to find it and then makes a new model from what data is does have (which at this point is just the id. So why isn't that happening with the post? It seems that the only notable difference between a `Loft` and a `TextPost` is that a `Loft` instance has no subclasses/subentities but a `Post` has several, included but not limited to `TextPost`, `ImagePost`, `VideoPost`, etc.

EDIT: When the user has made no posts so far, the call completes successfully. The same goes for if the first post is created and never cleared from the CoreData data store because MMRecord can just find that model by it's id.

**Comment by startupthekid** [comment]
I should add as an edit that when a user has made 0 posts so far, the call completes successfully.

**Comment by cnstoll** [comment]
Hi Brendan,

Based on what you've said here this sounds like a bug in MMRecord. I believe we attempted a fix for this in a draft branch for MMRecord 2.0.0, but development on that has paused and isn't scheduled to be resumed.

I believe you could work around this via subclassing if you really wanted to, but the best fix would likely be a patch to MMRecordResponse.

I'm going to assign this to the 1.4.2 milestone, but please note that there are not currently any development plans for completing that milestone. I'm just adding it to make it easier to keep track of the state of the library.

Thanks,

- Conrad

**Comment by startupthekid** [comment]
That's fine, this was 6 months ago anyway so I found other solutions.
