### ISSUE TITLE
Build error on example

### ISSUE THREAD

**Issue by hk05** [mutualmobile/MMRecord#103]
Being a new to MMRecord and swift, I wanted to check out MMRecord with swift. Just download the zip from github. Wanting to learn more from the MMRecordAtlassian example, I ran into build issues (using latest Xcode v6.1.1). 

Can anybody please check this out and fix the example(s)?

**Comment by cnstoll** [comment]
I'm going to go ahead and close this. We added the Swift example as a reference, and to test initial functionality of MMRecord with Swift. But Swift is changing faster than MMRecord is being updated, so maintaining that example project with the latest tools is going to be a losing battle.
