### ISSUE TITLE
100 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by adityajawa** [mutualmobile/MMRecord#112]
As soon as i am import the library, i start getting these errors.

duplicate symbol _MMRecordDebuggerParameterServerClassName in:
    /Users/mavericks/Library/Developer/Xcode/DerivedData/BeerUp-efoytrwiepewxadodooxromyngmr/Build/Intermediates/BeerUp.build/Debug-iphonesimulator/BeerUp.build/Objects-normal/x86_64/MMRecordProtoRecord.o
    /Users/mavericks/Library/Developer/Xcode/DerivedData/BeerUp-efoytrwiepewxadodooxromyngmr/Build/Intermediates/BeerUp.build/Debug-iphonesimulator/BeerUp.build/Objects-normal/x86_64/MMRecordDebugger.o
duplicate symbol _MMRecordDebuggerParameterKeyPathForResponseObject in:
    /Users/mavericks/Library/Developer/Xcode/DerivedData/BeerUp-efoytrwiepewxadodooxromyngmr/Build/Intermediates/BeerUp.build/Debug-iphonesimulator/BeerUp.build/Objects-normal/x86_64/MMRecordProtoRecord.o
    /Users/mavericks/Library/Developer/Xcode/DerivedData/BeerUp-efoytrwiepewxadodooxromyngmr/Build/Intermediates/BeerUp.build/Debug-iphonesimulator/BeerUp.build/Objects-normal/x86_64/MMRecordDebugger.o
ld: 100 duplicate symbols for architecture x86_64

**Comment by enmiller** [comment]
@adityajawa I believe this is related to a project settings flag in your project that was added in Xcode 6.3.x (not 100% sure what release of Xcode 6.3).  I am working on resolving this issue from within MMRecord.  

For now, in your project settings, search for "gcc_no" and set the flag to NO until we get the issue fixed.  That should allow you to build your project.
