### ISSUE TITLE
Testing in Swift - Invalid Entity Description

### ISSUE THREAD

**Issue by tkohout** [mutualmobile/MMRecord#117]
Hello!
I have some problems testing my program using MMRecord in Swift. Here is the error message I am having:

[MMRecord ERROR]-- Invalid Entity Description. This could be because this record class is not used in your managed object model, or because your persistent store coordinator or managed object model are not defined properly. An entity description is required for creating records..

And here is the test file:

    override func setUp() {
        super.setUp()
        GSServer.registerAFHTTPSessionManager(SessionManager.sharedInstance);
        GSRecord.registerServerClass(GSServer)
        MMRecord.setLoggingLevel(MMRecordLoggingLevel.All)
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    
    func testLoadNewsfeed() {
        var expectation = self.expectationWithDescription("Newsfeed loaded")
        
        var managedObjectContext = setUpInMemoryManagedObjectContext()
        Post.startPagedRequestWithURN("feed", data: nil, context: managedObjectContext, domain: self, resultBlock: { (record, pagemanager, requestNextPage) -> Void in
            expectation.fulfill()
        }) { (error) -> Void in
            
        }
        
     self.waitForExpectationsWithTimeout(5, handler: nil)
        
    }

And the in memory managed object context

     func setUpInMemoryManagedObjectContext() -> NSManagedObjectContext {
    let managedObjectModel = NSManagedObjectModel.mergedModelFromBundles([NSBundle.mainBundle()])!
    
    let persistentStoreCoordinator = NSPersistentStoreCoordinator(managedObjectModel: managedObjectModel)
    persistentStoreCoordinator.addPersistentStoreWithType(NSInMemoryStoreType, configuration: nil, URL: nil, options: nil, error: nil)
    
    let managedObjectContext = NSManagedObjectContext()
    managedObjectContext.persistentStoreCoordinator = persistentStoreCoordinator
    
    return managedObjectContext
    }

I tracked down the error to the `(NSEntityDescription *)MMRecord_entityForClass:(Class)managedObjectClass` which is called for initial entity (Post in this case) in `+ (NSArray*)recordsFromResponseObject:(id)responseObject` and returns nil. 

Now this happens only in Testing case, everything works as expected in the production environment.
I found that the modules might be the problem as written here: http://www.jessesquires.com/swift-coredata-and-testing/ but adding prefix to the class name didn't help.

Any idea what might be the problem and how to fix it?

The MMRecord version is 1.4.3. and swift version 1.1.

Thanks

**Comment by cnstoll** [comment]
Hi there,

Thank you for taking the time to write up this very detailed issue, and I'm sorry we haven't given it more investigation.

At this point we're not using MMRecord in any new Swift projects. So, while some testing has been done to just smoke test the library on Swift, this type of detail isn't something I have experienced personally. I wish I had a better answer, but I think the article you linked actually hits the nail on the head near the end. MMRecord is a very Objective-C style of dynamic interpretation of what is going on from an object population perspective. It may just turn out not to be the Swift way of doing things. I'm sure we'd do things differently in a Swift version of MMRecord, but right now that's not something we have planned.

Thanks,

- Conrad
