### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mhollis1980** [mutualmobile/MMRecord#119]
I'm looking building a sync system for a new project and I had a question about MMRecord. Is there a way to create local objects and have them pushed to the server or is this project a pull only?

Thanks,
Mike.

**Comment by ramonvic** [comment]
+1

**Comment by cnstoll** [comment]
That's a good question. The library is intended as a pull only type of interaction model, but I have seen people modify it to also execute post requests. That would be a very customized type of modification though, so not really something I see being added to the primary interface of the library.
